### ISSUE TITLE
Pequeña redundancia en validar.js

### ISSUE THREAD

**Issue by rnicar245** [Chaanchess/Examen-Diciembre-Cliente#1]
let datosEmpleado = function() {
        let nombre = document.getElementById("nombre").value;
        let fecha = document.getElementById("fecha").value;
        let dni = document.getElementById("dni").value;

Ya que tienes creadas variables que tienen almacenadas los input, podrías asignar a estas variables
locales el value de las otras.
Ejemplo: let nombre = nombre.value;

**Comment by lmagarin** [comment]
@rnicar245 Cuando crees los issues hazlo referenciando al código, no copiando el código
