### ISSUE TITLE
Problema con blur

### ISSUE THREAD

**Issue by alvaroolt** [Chaanchess/Examen-Diciembre-Cliente#9]
https://github.com/Chaanchess/Examen-Diciembre-Cliente/blob/02f0284e3437eb26092cf1a4eaff2b9a55159602/js/validar.js#L30
Hay un error y es que, cuando has rellenado todos los datos, si clicas en algún lugar de la página entre "nombre del empleado:" y el botón "Nuevo Empleado" se abre la página mostrando los datos introducidos.

**Comment by lmagarin** [comment]
@alvaroolt Qué error es este?? no lo entiendo...
